# Generated by Django 4.0 on 2021-12-23 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=200, unique=True)),
                ('organizer_uuid', models.UUIDField()),
                ('last_accessed_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_uuid', models.UUIDField()),
                ('offer_sdp', models.CharField(max_length=1000)),
                ('is_solved', models.BooleanField(default=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop_streaming.room', to_field='room_id')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_uuid', models.UUIDField()),
                ('offer_sdp', models.CharField(max_length=1000)),
                ('is_solved', models.BooleanField(default=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop_streaming.room', to_field='room_id')),
            ],
        ),
    ]
